apiVersion: 1

datasources:
  - name: SensorData
    type: frser-sqlite-datasource
    access: proxy
    url: file:/data/sensordata.db?cache=shared&mode=ro
    isDefault: true
    editable: true
    jsonData:
      path: /data/sensordata.db
